import { CustomerReview, Order, Product } from '@/types';
import { SELLER_CONFIG } from '@/lib/constants';

/**
 * Seed catalog. Prices, stock levels and fragrance notes are modelled on a real
 * Francistown boutique assortment and are safe to edit — the storefront reads
 * whichever record it finds locally (or in Supabase) at runtime.
 *
 * Image assets live in `public/products` and are authored at a 4:5 ratio.
 */
export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-rouge-seduction',
    title: 'Rouge Seduction Extrait de Parfum',
    slug: 'rouge-seduction-extrait-de-parfum',
    category: 'perfumes',
    description:
      'A luminous amber-floral extrait built on saffron, radiant jasmine and warm cedarwood. High oil concentration for all-day wear in the Botswana heat.',
    basePriceBWP: 280,
    isActive: true,
    isNewArrival: true,
    featuredTag: 'Top Seller',
    imageUrls: ['/products/rouge-1.jpg', '/products/rouge-2.jpg'],
    variants: [
      {
        id: 'var-rouge-30',
        productId: 'prod-rouge-seduction',
        sku: 'ROUGE-30ML',
        volumeMl: 30,
        scentProfile: 'Amber Floral & Saffron',
        priceBWP: 280,
        stockQuantity: 9,
        lowStockThreshold: 3,
      },
      {
        id: 'var-rouge-50',
        productId: 'prod-rouge-seduction',
        sku: 'ROUGE-50ML',
        volumeMl: 50,
        scentProfile: 'Amber Floral & Saffron',
        priceBWP: 420,
        stockQuantity: 4,
        lowStockThreshold: 3,
      },
      {
        id: 'var-rouge-100',
        productId: 'prod-rouge-seduction',
        sku: 'ROUGE-100ML',
        volumeMl: 100,
        scentProfile: 'Amber Floral & Saffron',
        priceBWP: 690,
        stockQuantity: 2,
        lowStockThreshold: 3,
      },
    ],
  },
  {
    id: 'prod-royal-oud',
    title: 'Royal Oud & Amber Intense',
    slug: 'royal-oud-amber-intense',
    category: 'perfumes',
    description:
      'Majestic Cambodian oud layered with smoky resin, Madagascar vanilla and amber crystals. Deep projection with a luxurious, long-lasting sillage.',
    basePriceBWP: 460,
    isActive: true,
    isNewArrival: false,
    featuredTag: 'Customer Favourite',
    imageUrls: ['/products/oud-1.jpg'],
    variants: [
      {
        id: 'var-oud-50',
        productId: 'prod-royal-oud',
        sku: 'OUD-50ML',
        volumeMl: 50,
        scentProfile: 'Smoky Oud & Amber',
        priceBWP: 460,
        stockQuantity: 2,
        lowStockThreshold: 2,
      },
      {
        id: 'var-oud-100',
        productId: 'prod-royal-oud',
        sku: 'OUD-100ML',
        volumeMl: 100,
        scentProfile: 'Smoky Oud & Amber',
        priceBWP: 750,
        stockQuantity: 0,
        lowStockThreshold: 2,
      },
    ],
  },
  {
    id: 'prod-warm-vanilla',
    title: 'Warm Vanilla Caramel Extrait',
    slug: 'warm-vanilla-caramel-extrait',
    category: 'perfumes',
    description:
      'A cosy gourmand of brown sugar, butterscotch and bourbon vanilla resting on creamy sandalwood. Sweet, warm and impossible to ignore.',
    basePriceBWP: 260,
    isActive: true,
    isNewArrival: true,
    featuredTag: 'Gourmand',
    imageUrls: ['/products/vanilla-1.jpg'],
    variants: [
      {
        id: 'var-vanilla-30',
        productId: 'prod-warm-vanilla',
        sku: 'VANILLA-30ML',
        volumeMl: 30,
        scentProfile: 'Warm Gourmand Vanilla',
        priceBWP: 260,
        stockQuantity: 11,
        lowStockThreshold: 3,
      },
      {
        id: 'var-vanilla-50',
        productId: 'prod-warm-vanilla',
        sku: 'VANILLA-50ML',
        volumeMl: 50,
        scentProfile: 'Warm Gourmand Vanilla',
        priceBWP: 390,
        stockQuantity: 7,
        lowStockThreshold: 3,
      },
    ],
  },
  {
    id: 'prod-linen-shirt',
    title: 'Oversized Breathable Linen Shirt',
    slug: 'oversized-breathable-linen-shirt',
    category: 'clothes',
    description:
      '100% premium lightweight linen cut for Botswana summers. Relaxed drop-shoulder silhouette with natural shell buttons and a soft washed finish.',
    basePriceBWP: 350,
    isActive: true,
    isNewArrival: true,
    featuredTag: 'Summer Essential',
    imageUrls: ['/products/shirt-1.jpg', '/products/shirt-2.jpg'],
    variants: [
      {
        id: 'var-shirt-cream-s',
        productId: 'prod-linen-shirt',
        sku: 'SHIRT-CREAM-S',
        size: 'S',
        color: 'Natural Cream',
        priceBWP: 350,
        stockQuantity: 6,
        lowStockThreshold: 2,
      },
      {
        id: 'var-shirt-cream-m',
        productId: 'prod-linen-shirt',
        sku: 'SHIRT-CREAM-M',
        size: 'M',
        color: 'Natural Cream',
        priceBWP: 350,
        stockQuantity: 5,
        lowStockThreshold: 2,
      },
      {
        id: 'var-shirt-cream-l',
        productId: 'prod-linen-shirt',
        sku: 'SHIRT-CREAM-L',
        size: 'L',
        color: 'Natural Cream',
        priceBWP: 350,
        stockQuantity: 2,
        lowStockThreshold: 2,
      },
      {
        id: 'var-shirt-olive-m',
        productId: 'prod-linen-shirt',
        sku: 'SHIRT-OLIVE-M',
        size: 'M',
        color: 'Safari Olive',
        priceBWP: 350,
        stockQuantity: 3,
        lowStockThreshold: 2,
      },
      {
        id: 'var-shirt-olive-xl',
        productId: 'prod-linen-shirt',
        sku: 'SHIRT-OLIVE-XL',
        size: 'XL',
        color: 'Safari Olive',
        priceBWP: 350,
        stockQuantity: 0,
        lowStockThreshold: 2,
      },
    ],
  },
  {
    id: 'prod-palazzo-trousers',
    title: 'High-Waisted Pleated Palazzo Trousers',
    slug: 'high-waisted-pleated-palazzo-trousers',
    category: 'clothes',
    description:
      'Wide-leg pleated trousers with a flattering high-waist band and deep pockets. Fluid drape that works for the office or a weekend in the city.',
    basePriceBWP: 380,
    isActive: true,
    isNewArrival: false,
    imageUrls: ['/products/palazzo-1.jpg'],
    variants: [
      {
        id: 'var-palazzo-mocha-s',
        productId: 'prod-palazzo-trousers',
        sku: 'PALAZZO-MOCHA-S',
        size: 'S',
        color: 'Rich Mocha',
        priceBWP: 380,
        stockQuantity: 5,
        lowStockThreshold: 2,
      },
      {
        id: 'var-palazzo-mocha-m',
        productId: 'prod-palazzo-trousers',
        sku: 'PALAZZO-MOCHA-M',
        size: 'M',
        color: 'Rich Mocha',
        priceBWP: 380,
        stockQuantity: 2,
        lowStockThreshold: 2,
      },
      {
        id: 'var-palazzo-black-l',
        productId: 'prod-palazzo-trousers',
        sku: 'PALAZZO-BLACK-L',
        size: 'L',
        color: 'Black',
        priceBWP: 380,
        stockQuantity: 4,
        lowStockThreshold: 2,
      },
    ],
  },
  {
    id: 'prod-shoulder-bag',
    title: 'Structured Leatherette Shoulder Bag',
    slug: 'structured-leatherette-shoulder-bag',
    category: 'accessories',
    description:
      'A minimalist shoulder baguette with brushed gold hardware, a zipped inner compartment and a comfortable padded strap.',
    basePriceBWP: 290,
    isActive: true,
    isNewArrival: true,
    imageUrls: ['/products/bag-1.jpg'],
    variants: [
      {
        id: 'var-bag-tan',
        productId: 'prod-shoulder-bag',
        sku: 'BAG-TAN',
        color: 'Tan',
        priceBWP: 290,
        stockQuantity: 8,
        lowStockThreshold: 2,
      },
      {
        id: 'var-bag-onyx',
        productId: 'prod-shoulder-bag',
        sku: 'BAG-ONYX-BLACK',
        color: 'Onyx Black',
        priceBWP: 290,
        stockQuantity: 3,
        lowStockThreshold: 2,
      },
    ],
  },
];

/** Verified buyer feedback powering the hero spotlight and product ratings. */
export const CUSTOMER_REVIEWS: CustomerReview[] = [
  {
    id: 'rev-rouge-1',
    productId: 'prod-rouge-seduction',
    customerName: 'Keabetswe M.',
    town: 'Francistown',
    rating: 5,
    comment:
      'Rouge Seduction lasts the whole day even in this heat. My colleagues keep asking what I am wearing.',
    date: '2026-09-05',
    verified: true,
  },
  {
    id: 'rev-rouge-2',
    productId: 'prod-rouge-seduction',
    customerName: 'Mpho T.',
    town: 'Gaborone',
    rating: 5,
    comment:
      'The saffron and amber notes are rich and sophisticated. Paying with Orange Money took seconds.',
    date: '2026-08-29',
    verified: true,
  },
  {
    id: 'rev-oud-1',
    productId: 'prod-royal-oud',
    customerName: 'Letsile K.',
    town: 'Francistown',
    rating: 5,
    comment:
      'This oud is the real deal — smoky and deep. Collected the same afternoon at Galo Mall.',
    date: '2026-09-07',
    verified: true,
  },
  {
    id: 'rev-vanilla-1',
    productId: 'prod-warm-vanilla',
    customerName: 'Bontle S.',
    town: 'Palapye',
    rating: 5,
    comment:
      'Warm Vanilla Caramel smells like dessert in a bottle. Sprint Couriers delivered to Palapye in two days.',
    date: '2026-09-01',
    verified: true,
  },
  {
    id: 'rev-vanilla-2',
    productId: 'prod-warm-vanilla',
    customerName: 'Amantle K.',
    town: 'Tonota',
    rating: 5,
    comment: 'Cosy, sweet and it never fades. I already ordered a second bottle for my sister.',
    date: '2026-09-09',
    verified: true,
  },
  {
    id: 'rev-shirt-1',
    productId: 'prod-linen-shirt',
    customerName: 'Tshiamo R.',
    town: 'Francistown',
    rating: 5,
    comment:
      'Perfect shirt for Francistown weather. Breathable linen and the relaxed fit still looks sharp.',
    date: '2026-09-08',
    verified: true,
  },
  {
    id: 'rev-shirt-2',
    productId: 'prod-linen-shirt',
    customerName: 'Naledi D.',
    town: 'Maun',
    rating: 4,
    comment:
      'Safari Olive is a gorgeous colour and the quality is superb. Runs generously, which I prefer.',
    date: '2026-09-04',
    verified: true,
  },
  {
    id: 'rev-bag-1',
    productId: 'prod-shoulder-bag',
    customerName: 'Lesego P.',
    town: 'Gaborone',
    rating: 5,
    comment:
      'Stunning for the price — the gold hardware lifts the whole outfit. Nationwide delivery was quick.',
    date: '2026-09-06',
    verified: true,
  },
];

/**
 * Demo order history so the operations dashboard is useful on first run.
 * Cleared by "Reset local store data" in the admin header.
 */
export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-demo-1',
    orderNumber: 'ORD-8421',
    customer: {
      name: 'Naledi Kgosi',
      phone: '+26772145892',
      town: 'Gaborone',
      address: 'Block 8, Plot 4210',
      deliveryPreference: 'nationwide_courier',
    },
    items: [
      {
        id: 'item-demo-1',
        productId: 'prod-rouge-seduction',
        variantId: 'var-rouge-50',
        productTitle: 'Rouge Seduction Extrait de Parfum',
        variantLabel: '50ml · Amber Floral & Saffron',
        unitPriceBWP: 420,
        quantity: 1,
        lineTotalBWP: 420,
      },
      {
        id: 'item-demo-2',
        productId: 'prod-linen-shirt',
        variantId: 'var-shirt-cream-m',
        productTitle: 'Oversized Breathable Linen Shirt',
        variantLabel: 'M · Natural Cream',
        unitPriceBWP: 350,
        quantity: 1,
        lineTotalBWP: 350,
      },
    ],
    subtotalBWP: 770,
    deliveryFeeBWP: 80,
    totalAmountBWP: 850,
    paymentMethod: 'orange_money',
    status: 'pending_verification',
    createdAt: '2026-09-11T09:42:00.000Z',
    verificationNotes: 'Customer says transfer reference OM-984102 was sent at 09:40.',
  },
  {
    id: 'ord-demo-2',
    orderNumber: 'ORD-8420',
    customer: {
      name: 'Kagiso Tshekedi',
      phone: '+26774889123',
      town: 'Francistown',
      address: 'Somerset Extension, near Choppies',
      deliveryPreference: 'local_courier',
    },
    items: [
      {
        id: 'item-demo-3',
        productId: 'prod-royal-oud',
        variantId: 'var-oud-50',
        productTitle: 'Royal Oud & Amber Intense',
        variantLabel: '50ml · Smoky Oud & Amber',
        unitPriceBWP: 460,
        quantity: 1,
        lineTotalBWP: 460,
      },
    ],
    subtotalBWP: 460,
    deliveryFeeBWP: 45,
    totalAmountBWP: 505,
    paymentMethod: 'fnb_pay2cell',
    status: 'payment_confirmed',
    createdAt: '2026-09-11T07:15:00.000Z',
    verifiedAt: '2026-09-11T07:22:00.000Z',
  },
  {
    id: 'ord-demo-3',
    orderNumber: 'ORD-8419',
    customer: {
      name: 'Boipelo Raditladi',
      phone: '+26771556677',
      town: 'Francistown',
      address: 'Nswazwi Mall pickup point',
      deliveryPreference: 'francistown_pickup',
    },
    items: [
      {
        id: 'item-demo-4',
        productId: 'prod-palazzo-trousers',
        variantId: 'var-palazzo-mocha-m',
        productTitle: 'High-Waisted Pleated Palazzo Trousers',
        variantLabel: 'M · Rich Mocha',
        unitPriceBWP: 380,
        quantity: 1,
        lineTotalBWP: 380,
      },
    ],
    subtotalBWP: 380,
    deliveryFeeBWP: 0,
    totalAmountBWP: 380,
    paymentMethod: 'cash_on_pickup',
    status: 'dispatched',
    createdAt: '2026-09-10T14:00:00.000Z',
    verifiedAt: '2026-09-10T14:10:00.000Z',
  },
  {
    id: 'ord-demo-4',
    orderNumber: 'ORD-8418',
    customer: {
      name: 'Thabo Motswaledi',
      phone: '+26776112233',
      town: 'Maun',
      address: 'Boseja Ward',
      deliveryPreference: 'nationwide_courier',
    },
    items: [
      {
        id: 'item-demo-5',
        productId: 'prod-warm-vanilla',
        variantId: 'var-vanilla-50',
        productTitle: 'Warm Vanilla Caramel Extrait',
        variantLabel: '50ml · Warm Gourmand Vanilla',
        unitPriceBWP: 390,
        quantity: 2,
        lineTotalBWP: 780,
      },
    ],
    subtotalBWP: 780,
    deliveryFeeBWP: 80,
    totalAmountBWP: 860,
    paymentMethod: 'orange_money',
    status: 'completed',
    createdAt: '2026-09-09T10:00:00.000Z',
    verifiedAt: '2026-09-09T10:15:00.000Z',
  },
];

/** Copy used in the storefront hero trust bar. */
export const TRUST_BAR_ITEMS = [
  'Free Francistown Pickups',
  'Nationwide Sprint Couriers',
  'Authentic Guarantee',
] as const;

/** Seller WhatsApp handset reused in structured data. */
export const STORE_PHONE = SELLER_CONFIG.sellerWhatsApp;
