import { Product, Order, CustomerReview } from '@/types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    title: 'Rouge Seduction Extrait de Parfum',
    slug: 'rouge-seduction-extrait',
    category: 'perfumes',
    description: 'A luminous and sophisticated amber-floral fragrance with rich saffron, cedarwood, and radiant jasmine notes. Long-lasting oil-based formula.',
    basePriceBWP: 280,
    isActive: true,
    isNewArrival: true,
    featuredTag: 'Top Seller',
    imageUrls: [
      '/products/rouge-1.jpg',
      '/products/rouge-2.jpg',
    ],
    variants: [
      {
        id: 'var-101',
        productId: 'prod-1',
        sku: 'ROUGE-30ML',
        volumeMl: 30,
        scentProfile: 'Amber Floral & Saffron',
        priceBWP: 280,
        stockQuantity: 8,
        lowStockThreshold: 3,
      },
      {
        id: 'var-102',
        productId: 'prod-1',
        sku: 'ROUGE-50ML',
        volumeMl: 50,
        scentProfile: 'Amber Floral & Saffron',
        priceBWP: 420,
        stockQuantity: 4,
        lowStockThreshold: 3,
      },
      {
        id: 'var-103',
        productId: 'prod-1',
        sku: 'ROUGE-100ML',
        volumeMl: 100,
        scentProfile: 'Amber Floral & Saffron',
        priceBWP: 690,
        stockQuantity: 2,
        lowStockThreshold: 3,
      },
    ],
  },
  {
    id: 'prod-2',
    title: 'Royal Oud & Amber Intense',
    slug: 'royal-oud-amber-intense',
    category: 'perfumes',
    description: 'Majestic Cambodian oud infused with deep smoky resin, Madagascar vanilla, and warm amber crystals. High projection and luxury sillage.',
    basePriceBWP: 320,
    isActive: true,
    isNewArrival: false,
    featuredTag: 'Customer Favorite',
    imageUrls: [
      '/products/oud-1.jpg',
    ],
    variants: [
      {
        id: 'var-201',
        productId: 'prod-2',
        sku: 'OUD-50ML',
        volumeMl: 50,
        scentProfile: 'Smoky Oud & Amber',
        priceBWP: 460,
        stockQuantity: 5,
        lowStockThreshold: 2,
      },
      {
        id: 'var-202',
        productId: 'prod-2',
        sku: 'OUD-100ML',
        volumeMl: 100,
        scentProfile: 'Smoky Oud & Amber',
        priceBWP: 750,
        stockQuantity: 1, // Low stock demo
        lowStockThreshold: 2,
      },
    ],
  },
  {
    id: 'prod-3',
    title: 'Warm Vanilla Caramel Extrait',
    slug: 'warm-vanilla-caramel',
    category: 'perfumes',
    description: 'A cozy, edible gourmand blend of brown sugar, butterscotch, bourbon vanilla, and sandalwood. Intoxicating and feminine.',
    basePriceBWP: 260,
    isActive: true,
    isNewArrival: true,
    imageUrls: [
      '/products/vanilla-1.jpg',
    ],
    variants: [
      {
        id: 'var-301',
        productId: 'prod-3',
        sku: 'VAN-30ML',
        volumeMl: 30,
        scentProfile: 'Warm Gourmand Vanilla',
        priceBWP: 260,
        stockQuantity: 9,
        lowStockThreshold: 3,
      },
      {
        id: 'var-302',
        productId: 'prod-3',
        sku: 'VAN-50ML',
        volumeMl: 50,
        scentProfile: 'Warm Gourmand Vanilla',
        priceBWP: 390,
        stockQuantity: 6,
        lowStockThreshold: 3,
      },
    ],
  },
  {
    id: 'prod-4',
    title: 'Oversized Breathable Linen Shirt',
    slug: 'oversized-linen-shirt',
    category: 'clothes',
    description: '100% natural premium lightweight linen crafted for Botswana summer weather. Relaxed drop shoulder silhouette with shell button accents.',
    basePriceBWP: 350,
    isActive: true,
    isNewArrival: true,
    featuredTag: 'Summer Essential',
    imageUrls: [
      '/products/shirt-1.jpg',
      '/products/shirt-2.jpg',
    ],
    variants: [
      {
        id: 'var-401',
        productId: 'prod-4',
        sku: 'SHIRT-CREAM-S',
        size: 'S',
        color: 'Natural Cream',
        priceBWP: 350,
        stockQuantity: 6,
        lowStockThreshold: 2,
      },
      {
        id: 'var-402',
        productId: 'prod-4',
        sku: 'SHIRT-CREAM-M',
        size: 'M',
        color: 'Natural Cream',
        priceBWP: 350,
        stockQuantity: 4,
        lowStockThreshold: 2,
      },
      {
        id: 'var-403',
        productId: 'prod-4',
        sku: 'SHIRT-CREAM-L',
        size: 'L',
        color: 'Natural Cream',
        priceBWP: 350,
        stockQuantity: 2,
        lowStockThreshold: 2,
      },
      {
        id: 'var-404',
        productId: 'prod-4',
        sku: 'SHIRT-OLIVE-M',
        size: 'M',
        color: 'Safari Olive',
        priceBWP: 350,
        stockQuantity: 3,
        lowStockThreshold: 2,
      },
      {
        id: 'var-405',
        productId: 'prod-4',
        sku: 'SHIRT-OLIVE-XL',
        size: 'XL',
        color: 'Safari Olive',
        priceBWP: 350,
        stockQuantity: 0, // Sold out demo
        lowStockThreshold: 2,
      },
    ],
  },
  {
    id: 'prod-5',
    title: 'High-Waisted Pleated Palazzo Trousers',
    slug: 'pleated-palazzo-trousers',
    category: 'clothes',
    description: 'Elevated wide-leg flowing trousers with a flattering high-waist band and deep pockets. Pairs seamlessly with crop tops or oversized blazers.',
    basePriceBWP: 380,
    isActive: true,
    isNewArrival: false,
    imageUrls: [
      '/products/palazzo-1.jpg',
    ],
    variants: [
      {
        id: 'var-501',
        productId: 'prod-5',
        sku: 'PANT-MOCHA-S',
        size: 'S',
        color: 'Rich Mocha',
        priceBWP: 380,
        stockQuantity: 5,
        lowStockThreshold: 2,
      },
      {
        id: 'var-502',
        productId: 'prod-5',
        sku: 'PANT-MOCHA-M',
        size: 'M',
        color: 'Rich Mocha',
        priceBWP: 380,
        stockQuantity: 2,
        lowStockThreshold: 2,
      },
      {
        id: 'var-503',
        productId: 'prod-5',
        sku: 'PANT-BLACK-L',
        size: 'L',
        color: 'Midnight Black',
        priceBWP: 380,
        stockQuantity: 4,
        lowStockThreshold: 2,
      },
    ],
  },
  {
    id: 'prod-6',
    title: 'Structured Leatherette Shoulder Bag',
    slug: 'structured-shoulder-bag',
    category: 'accessories',
    description: 'Minimalist chic everyday baguette bag with gold metal hardware, zippered inner compartment, and comfortable shoulder strap.',
    basePriceBWP: 290,
    isActive: true,
    isNewArrival: true,
    imageUrls: [
      '/products/bag-1.jpg',
    ],
    variants: [
      {
        id: 'var-601',
        productId: 'prod-6',
        sku: 'BAG-TAN',
        color: 'Caramel Tan',
        priceBWP: 290,
        stockQuantity: 7,
        lowStockThreshold: 2,
      },
      {
        id: 'var-602',
        productId: 'prod-6',
        sku: 'BAG-BLK',
        color: 'Onyx Black',
        priceBWP: 290,
        stockQuantity: 3,
        lowStockThreshold: 2,
      },
    ],
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1',
    orderNumber: 'ORD-8421',
    customer: {
      fullName: 'Naledi Kgosi',
      phone: '72145892',
      deliveryTown: 'Gaborone',
      deliveryAddress: 'Block 8, Plot 4210',
      deliveryPreference: 'local_courier',
    },
    items: [
      {
        id: 'item-1',
        productId: 'prod-1',
        variantId: 'var-102',
        productTitle: 'Rouge Seduction Extrait',
        variantLabel: '50ml (Amber Floral)',
        unitPriceBWP: 420,
        quantity: 1,
        lineTotalBWP: 420,
      },
      {
        id: 'item-2',
        productId: 'prod-4',
        variantId: 'var-402',
        productTitle: 'Oversized Breathable Linen Shirt',
        variantLabel: 'Size M / Natural Cream',
        unitPriceBWP: 350,
        quantity: 1,
        lineTotalBWP: 350,
      },
    ],
    subtotalBWP: 770,
    deliveryFeeBWP: 45,
    totalAmountBWP: 815,
    paymentMethod: 'orange_money',
    status: 'pending_verification',
    createdAt: '2026-09-11T14:30:00Z',
    verificationNotes: 'Customer sent transfer reference OM-984102',
  },
  {
    id: 'ord-2',
    orderNumber: 'ORD-8420',
    customer: {
      fullName: 'Kagiso Tshekedi',
      phone: '74889123',
      deliveryTown: 'Francistown',
      deliveryAddress: 'Somerset Extension, Near Choppies',
      deliveryPreference: 'local_courier',
    },
    items: [
      {
        id: 'item-3',
        productId: 'prod-2',
        variantId: 'var-201',
        productTitle: 'Royal Oud & Amber Intense',
        variantLabel: '50ml (Smoky Oud)',
        unitPriceBWP: 460,
        quantity: 1,
        lineTotalBWP: 460,
      },
    ],
    subtotalBWP: 460,
    deliveryFeeBWP: 45,
    totalAmountBWP: 505,
    paymentMethod: 'fnb_pay2cell',
    status: 'payment_confirmed',
    createdAt: '2026-09-11T12:15:00Z',
    verifiedAt: '2026-09-11T12:22:00Z',
  },
  {
    id: 'ord-3',
    orderNumber: 'ORD-8419',
    customer: {
      fullName: 'Boipelo Raditladi',
      phone: '71556677',
      deliveryTown: 'Tati Siding',
      deliveryAddress: 'Near Shell Station & Primary School',
      deliveryPreference: 'collection',
    },
    items: [
      {
        id: 'item-4',
        productId: 'prod-5',
        variantId: 'var-502',
        productTitle: 'Pleated Palazzo Trousers',
        variantLabel: 'Size M / Rich Mocha',
        unitPriceBWP: 380,
        quantity: 1,
        lineTotalBWP: 380,
      },
    ],
    subtotalBWP: 380,
    deliveryFeeBWP: 0,
    totalAmountBWP: 380,
    paymentMethod: 'orange_money',
    status: 'ready_for_pickup',
    createdAt: '2026-09-10T16:00:00Z',
    verifiedAt: '2026-09-10T16:10:00Z',
  },
  {
    id: 'ord-4',
    orderNumber: 'ORD-8418',
    customer: {
      fullName: 'Thabo Motswaledi',
      phone: '76112233',
      deliveryTown: 'Maun',
      deliveryAddress: 'Boseja Ward',
      deliveryPreference: 'local_courier',
    },
    items: [
      {
        id: 'item-5',
        productId: 'prod-1',
        variantId: 'var-103',
        productTitle: 'Rouge Seduction Extrait',
        variantLabel: '100ml (Amber Floral)',
        unitPriceBWP: 690,
        quantity: 1,
        lineTotalBWP: 690,
      },
    ],
    subtotalBWP: 690,
    deliveryFeeBWP: 45,
    totalAmountBWP: 735,
    paymentMethod: 'fnb_pay2cell',
    status: 'out_for_delivery',
    createdAt: '2026-09-10T10:00:00Z',
    verifiedAt: '2026-09-10T10:15:00Z',
  },
  {
    id: 'ord-5',
    orderNumber: 'ORD-8415',
    customer: {
      fullName: 'Tefo Sebele',
      phone: '72998877',
      deliveryTown: 'Gaborone',
      deliveryAddress: 'CBD iTowers meetup',
      deliveryPreference: 'in_person_meetup',
    },
    items: [
      {
        id: 'item-6',
        productId: 'prod-6',
        variantId: 'var-601',
        productTitle: 'Structured Leatherette Bag',
        variantLabel: 'Caramel Tan',
        unitPriceBWP: 290,
        quantity: 1,
        lineTotalBWP: 290,
      },
    ],
    subtotalBWP: 290,
    deliveryFeeBWP: 25,
    totalAmountBWP: 315,
    paymentMethod: 'orange_money',
    status: 'completed',
    createdAt: '2026-09-09T11:00:00Z',
    verifiedAt: '2026-09-09T11:15:00Z',
  },
];

export const CUSTOMER_REVIEWS: CustomerReview[] = [
  {
    id: 'rev-1',
    productId: 'prod-1',
    customerName: 'Keabetswe M.',
    town: 'Francistown',
    rating: 5,
    comment: 'The Rouge Seduction is absolutely divine! The sillage lasts all day even in our Botswana heat. My colleagues keep asking what I\'m wearing. Will definitely repurchase the 100ml.',
    date: '2026-09-05',
    verified: true,
  },
  {
    id: 'rev-2',
    productId: 'prod-1',
    customerName: 'Mpho T.',
    town: 'Gaborone',
    rating: 5,
    comment: 'Best niche perfume I\'ve found in Botswana. The amber saffron notes are rich and sophisticated. Orange Money payment was seamless!',
    date: '2026-09-03',
    verified: true,
  },
  {
    id: 'rev-3',
    productId: 'prod-2',
    customerName: 'Letsile K.',
    town: 'Tati Siding',
    rating: 5,
    comment: 'This oud is the real deal — smoky, deep, masculine. Picked up from Tati Siding same day. NeoSales customer service is top-notch!',
    date: '2026-09-07',
    verified: true,
  },
  {
    id: 'rev-4',
    productId: 'prod-3',
    customerName: 'Bontle S.',
    town: 'Palapye',
    rating: 5,
    comment: 'The Warm Vanilla Caramel smells like heaven! Sweet but not overpowering. Sprint Courier delivered to Palapye in 2 days.',
    date: '2026-09-01',
    verified: true,
  },
  {
    id: 'rev-5',
    productId: 'prod-4',
    customerName: 'Tshiamo R.',
    town: 'Francistown',
    rating: 5,
    comment: 'Perfect summer shirt for Francistown weather. The linen is breathable and the fit is relaxed but still looks sharp. Ordered via FNB Pay2Cell — zero stress.',
    date: '2026-09-08',
    verified: true,
  },
  {
    id: 'rev-6',
    productId: 'prod-4',
    customerName: 'Naledi D.',
    town: 'Maun',
    rating: 4,
    comment: 'Love the quality and the Safari Olive colour is gorgeous. Runs slightly oversized which I actually prefer. Nationwide delivery was fast!',
    date: '2026-09-04',
    verified: true,
  },
  {
    id: 'rev-7',
    productId: 'prod-6',
    customerName: 'Lesego P.',
    town: 'Gaborone',
    rating: 5,
    comment: 'This bag is stunning for the price! The gold hardware gives it a luxury feel. Picked it up at Galo Mall — such a convenient system.',
    date: '2026-09-06',
    verified: true,
  },
  {
    id: 'rev-8',
    productId: 'prod-3',
    customerName: 'Amantle K.',
    town: 'Tonota',
    rating: 5,
    comment: 'I get so many compliments wearing the Vanilla Caramel! It\'s cozy, sweet, and lasts forever. Already ordered a second bottle for my sister.',
    date: '2026-09-09',
    verified: true,
  },
];
