#:schema node_modules/wrangler/config-schema.json
name = "neosales"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]
[assets]
directory = "./out"
not_found_handling = "single-page-application"

[vars]
NEXT_PUBLIC_STORE_NAME = "NeoSales"
NEXT_PUBLIC_SELLER_WHATSAPP = "+26771550200"
NEXT_PUBLIC_ORANGE_MONEY_NUMBER = "74453342"
NEXT_PUBLIC_FNB_PAY2CELL_NUMBER = "71550200"
NEXT_PUBLIC_FNB_ACCOUNT_NAME = "NeoSales Retail"
NEXT_PUBLIC_SUPABASE_URL = "https://hqnwxckuptagvsizanho.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhxbnd4Y2t1cHRhZ3ZzaXphbmhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEzNjA4NzgsImV4cCI6MjA5NjkzNjg3OH0.hperV86cE_hUkPykQX0ma7GyFJ12DPd55FJafzJRodk"
